[package]
name = "nml-lsp"
description = "Language Server Protocol implementation for NML"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nml-core = { workspace = true }
nml-validate = { workspace = true }
nml-fmt = { workspace = true }
serde_json = { workspace = true }
tower-lsp = { workspace = true }
tokio = { workspace = true }
